services:
  db:
    image: postgres:16
    container_name: postgres-warehouse
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: warehouse
      POSTGRES_PASSWORD: warehouse
      POSTGRES_DB: warehouse
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
